### ISSUE TITLE
Edit buttons?

### ISSUE THREAD

**Issue by cimspin** [PilotsTradeNetwork/ButtonRoleBot#18]
A lot of effort for what could just be a remove/re-add, but should probably add it at some point.

**Comment by TuggyBoat** [comment]
The components of the message (`message.components`) are stored as ActionRow objects, with buttons being able to got from `ActionRow.children`, this will probably be used the most for the edit command

**Comment by cimspin** [comment]
If we get the view with `View.from_message` can iterate through `view.children` for `isinstance(child, discord.ui.DynamicItem)` to retrieve the dynamic buttons off a view

**Comment by TuggyBoat** [comment]
Tried that, however it seems like when inserted into a view they become `discord.ui.Button` objects
