### ISSUE TITLE
Handle error code 50035: Invalid Form Body In components.0.components.1.emoji.name: Invalid emoji

### ISSUE THREAD

**Issue by TuggyBoat** [PilotsTradeNetwork/ButtonRoleBot#25]
Error for when an invalid emoji is passed for a button

**Comment by cimspin** [comment]
Also "400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.1.custom_id: Component custom id cannot be duplicated" for duplicate custom_id

**Comment by cimspin** [comment]
Looks like these come under the generic [HTTPException](https://discordpy.readthedocs.io/en/stable/api.html?highlight=forbidden#discord.HTTPException) class.
