### ISSUE TITLE
Remove individual buttons

### ISSUE THREAD

**Issue by TuggyBoat** [PilotsTradeNetwork/ButtonRoleBot#57]

**Comment by cimspin** [comment]
Explain?

**Comment by TuggyBoat** [comment]
Rather than removing all the buttons at once, why not provide a list of buttons that they can remove? So they don't have to remake buttons if they just want to delete one

**Comment by cimspin** [comment]
Oh, now I understand what you mean! On reflection, I'm leaning in the direction of an edit command as per #18 that could pull double duty to remove/edit buttons individually or en masse.
